[project]
name = "complaint-intelligence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rapipon", email = "rodvasbiev@yandex.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.5",
]

[project.scripts]
complaint-intelligence = "complaint_intelligence:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
